// Code generated by "stringer -type=BaGua"; DO NOT EDIT.

package data

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Kan-1]
	_ = x[Kun-2]
	_ = x[Zhen-3]
	_ = x[Xun-4]
	_ = x[Zhong-5]
	_ = x[Qian-6]
	_ = x[Dui-7]
	_ = x[Gen-8]
	_ = x[Li-9]
}

const _BaGua_name = "KanKunZhenXunZhongQianDuiGenLi"

var _BaGua_index = [...]uint8{0, 3, 6, 10, 13, 18, 22, 25, 28, 30}

func (i BaGua) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_BaGua_index)-1 {
		return "BaGua(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaGua_name[_BaGua_index[idx]:_BaGua_index[idx+1]]
}
